### ISSUE TITLE
parameter in SASManager.shared.verifySASServer won't work 

### ISSUE THREAD

**Issue by MikeHeidemann** [sassoftware/sas-sdk-for-iOS-examples#10]
Hi all,
this my first try to work with XCode and the SAS SDK for iOS. I download the latest SASKit from the sas.developer site and the sas-sdk-for-iOS-examples. I load the Workspace "SASKit-Samples.xcworkspace" into XCode and can successfully build and run the first example "SASKitCustomApp".  Every try to build another examples like "SASKitFullscreen" failed with this messages "Cannot convert value of type 'URL' to expected argument type 'SASServerDescriptor".

SASKitFullscreen -> AppDelegate.swift: in function handleReportAvailable() (line 41:96). The error occurs in the call "SASManager.shared.verifySASServer( url )" in line 53. 

Have someone any idea what is wrong in my configuration?

thanks
Mike

**Comment by rchogan** [comment]
Hi Mike,

Thanks for pointing this out.  We changed our API, and forgot to update these samples to reflect the new usage.   I have pushed a commit that fixes the problem, and uses the new SASServerDescriptor API.

https://github.com/sassoftware/sas-sdk-for-iOS-examples/commit/9e3631eaa087906fd387c1a14f45a7d99f90c88a

Don't hesitate to post back here if you run into any other problems!

Rich

**Comment by MikeHeidemann** [comment]
Hi Rich,
now it works :) 

br
Mike
