### ISSUE TITLE
Old link to SASKit documentation on README.md

### ISSUE THREAD

**Issue by egoienola** [sassoftware/sas-sdk-for-iOS-examples#11]
README currently points reader to SASKit Documentation URL for version 8.22: https://developer.sas.com/sdk/mobile/iOS/doc/8.22/

Should it be updated with the latest URL?:
https://developer.sas.com/sdk/mobile/iOS/doc/current/api-doc/

**Comment by rchogan** [comment]
Thanks for the heads up.  I have updated the links.
