### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by kraussjo** [sassoftware/sas-sdk-for-iOS-examples#2]
Hello :-),

i have a Problem running the Installation of the Examples. I use XCode 9.3 and the newest SASKit Installer 8.22.

I am getting the following error while building a project:

_Module compiled with Swift 4.0.3 cannot be imported in Swift 3.3: /sas-sdk-for-iOS-examples-master/SASKitCustomApp/SASKit.framework/Modules/SASKit.swiftmodule/x86_64.swiftmodule_

I downloaded the Toolchain of XCode 4.03, it is building, but then I am getting the following error when Start the App in the Simulator:

_dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/../Library/Developer/CoreSimulator/Devices/16840D14-5862-413C-9BE7-A80E0CE157FA/data/Containers/Bundle/Application/4D772C7C-2F98-4847-AD07-3A944042420B/SASKitCustomApp.app/Frameworks/SASKit.framework/SASKit
  Reason: Incompatible library version: SASKit requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0_

I'm new in iOS programming, so please be patient ;-)

Thanks alot
Jochen

**Comment by kraussjo** [comment]
Hi rchogan !

Thanks, it works now with XCode 9.2. Now, i have to learn and understand the Use of SASKit to integrate our VA Reports or to customise the SAS App.

Thanks alot
Jochen

**Comment by rchogan** [comment]
Glad you got it working!
