### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by kraussjo** [sassoftware/sas-sdk-for-iOS-examples#6]
Hi all,

once again, thanks a lot for that extensive examples. I have configured XCode, and it works nice!

Next step was to integrate our VA 8.2 Server into some small app, based on your Master-Detail Example. 

First Question: I can connect the Server via http but not with https. The server is running in AWS. Do I need a certificate?

Second Question: I don't want to hardcoded the server address and the user credentials in my code. I know, there is the sas-sdk-servers.json, but how can i tap it in my app?

Is it ok, to ask this question here? Or should i go to to the VA community? But i think, my questions are very special.

My company and I are new in iOS Development, but we want to use the benefit of the SASkit with our VA Clients. So, sorry for some Questions ;-)

Thanks a lot

**Comment by rchogan** [comment]
Hi kraussjo,

By all means, questions here are great.   We are happy to get the feedback, and help you out! 

For your first question, yes, you will need a certificate installed on your device for that server.

For your second question, there will be an API for this feature in the upcoming June release.  Until then, if you are familiar with replacing the sas-sdk-servers.json file in the framework, that will work for now, although will not be directly supported in future versions of the SDK.   If you have issues with that, or need more help, feel free to send me a direct message  _Rich **dot** Hogan@sas **dot** com_ (email mangled to avoid spam bots...)
